// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1geCIcyhDBqJUwC8eMbumWWbsDpGj5vk',
    appId: '1:872563427812:android:5b55c8e463edca8ec5dff1',
    messagingSenderId: '872563427812',
    projectId: 'fluttersocialmedia-aa0e6',
    databaseURL: 'https://fluttersocialmedia-aa0e6-default-rtdb.firebaseio.com',
    storageBucket: 'fluttersocialmedia-aa0e6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDxwiDyrhLLhq9OgmAlHryDIEHFK-4VqA',
    appId: '1:872563427812:ios:e9dd2eaceb9beab1c5dff1',
    messagingSenderId: '872563427812',
    projectId: 'fluttersocialmedia-aa0e6',
    databaseURL: 'https://fluttersocialmedia-aa0e6-default-rtdb.firebaseio.com',
    storageBucket: 'fluttersocialmedia-aa0e6.appspot.com',
    iosClientId: '872563427812-196pdqm5qdgk97kv9e37t8nh3ee4hh98.apps.googleusercontent.com',
    iosBundleId: 'com.edugram.edugramV1',
  );
}
